export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_FAILURE = "CREATE_MESSAGE_FAILURE";
