export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const SEND_MESSAGE = "RECEIVE_MESSAGE";
